general {
    disable_loading_bar = true
    grace = 0
    hide_cursor = true
}

background {
    monitor =
    path = /home/kazte/Wallpapers/current/guts-berserk-neon-3840x2160-19140.jpg
    blur_passes = 2
    blur_size = 6

    noise = 0.0117
    contrast = 1.1
    brightness = 0.7

    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2

    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(120, 0, 0, 0.9)
    inner_color = rgba(0, 0, 0, 0.6)
    font_color = rgb(220, 220, 220)

    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4">Password...</span>

    position = 0, -120
    halign = center
    valign = center
}

# Hora
label {
    monitor =
    text = cmd[update:1000] date +'%H:%M'
    color = rgb(220, 220, 220)
    font_size = 64

    position = 0, 80
    halign = center
    valign = center
}

# Fecha en inglés
label {
    monitor =
    text = cmd[update:60000] LC_TIME=en_US.UTF-8 date +'%A %d %B'
    color = rgb(180, 180, 180)
    font_size = 20

    position = 0, 30
    halign = center
    valign = center
}
